City-of-Helsinki/palvelutarjotin-ui

- src/domain/event/eventBasicInfo/EventBasicInfo.tsx
- src/utils/__tests__/addUrlSlashes.test.ts
- src/utils/addUrlSlashes.ts
- Add //-prefix to url if protocol is missing from it (so that browser knows it is an external url)
**[PT-411](https://helsinkisolutionoffice.atlassian.net/browse/PT-411):**
> PT-411 | Add url slashes to event url if protocol missing

- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/enrolment/occurrenceTable/OccurrenceTable.tsx
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/occurrences/Occurrences.tsx
- Present seats left so that it is more understandable. Instead of showing 0/100 seats left (which meant 100 places left) show 100/100 seats left
**[PT-586](https://helsinkisolutionoffice.atlassian.net/browse/PT-586):**
> PT-586 | Improve how seats left is presented

- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/ValidationSchema.tsx
- src/domain/enrolment/enrolmentForm/constants.ts
- src/domain/enrolment/utils.ts
- src/domain/studyGroup/query.ts
- src/domain/studyLevel/query.ts
- src/domain/studyLevel/useStudyLevels.ts
- src/generated/graphql.tsx
- src/utils/mockDataUtils.ts
PT-728 PT-730. Added new queries for StudyLevel schema and updated it to StudyGroup also. New graphql.tsx is generated, mockDataUtil is updated with new study level mock tools and Enrolment form and the tests related to it are updated.
NOTE: Please note that request is into PT-683-age-dropdown-multiselect -branch. This pull request should full fill the pull request #66
> Added a new StudyLevel schema.

- public/static/locales/en/form.json
- public/static/locales/fi/form.json
- public/static/locales/sv/form.json
- src/domain/app/forms/constants.ts
- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/enrolment/enrolmentForm/ValidationSchema.tsx
PT-798 Added the missing validation against minimum  group size validation. If the total count in under minimum required, same validation message will appear under both the study group count fields.
Issue: https://helsinkisolutionoffice.atlassian.net/browse/PT-798
Other validation cases here (in a linked task): https://helsinkisolutionoffice.atlassian.net/browse/PT-772?focusedCommentId=19250
> Added a validation against minimum  group size validation.

- src/domain/occurrence/utils.ts
PT-807 Earlier versions of app filled the event with children only. Now when the adults are added to total seats taken calculation, some negative numbers started to appear. This fix returns 0 instead of negative space left.
Before:
> Show zero instead of a negative amount as space left in a study group.

- src/domain/event/eventCard/EventCard.tsx
- src/domain/event/eventKeywords/EventKeywords.tsx
- src/domain/event/utils.ts
- src/domain/events/eventList/EventList.tsx
- src/domain/events/query.ts
- src/domain/events/utils.ts
- src/generated/graphql.tsx
- src/utils/mockDataUtils.ts
PT-797 Removed pEvent and venue fields (but left an id and nextOccurrenceDatetime) to much improve the events query. Single event query is unchanged.
API changes done in https://github.com/City-of-Helsinki/palvelutarjotin/pull/129.
> Improved events query.

- src/domain/enrolment/CreateEnrolmentPage.tsx
- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
PT-842 Fixed enrolment creation page. Keywords must be included in events query like they are in event page.
> Critical fix to create enrolment page's event query.

- public/static/locales/en/event.json
- public/static/locales/en/occurrence.json
- public/static/locales/fi/event.json
- public/static/locales/fi/occurrence.json
- public/static/locales/sv/event.json
- public/static/locales/sv/occurrence.json
- src/domain/event/EventPage.tsx
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/eventBasicInfo/EventCategorisation.tsx
- src/domain/event/occurrences/Occurrences.tsx
- src/domain/event/utils.ts
- src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupInfo.tsx
- src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupLanguageInfo.tsx
PT-830. In language field is now included in event query and the languages are listed in category section because it was designed there and the field works exactly the same as keywords. Changes to how the group info with language is shown on occurrence. Added labels for seats taken and language. Some changes to translations.
> Rendered event languages on event page

- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/enrolment/occurrenceTable/OccurrenceTable.tsx
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/occurrences/Occurrences.tsx
PT-790. Weekday shown in title table row in format "dd.MM.yyyy eeeeee", e.g "24.03.2021 We".
> Showing weekday on occurrence table titles.

- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/occurrences/Occurrences.tsx
- src/domain/event/utils.ts
PT-911 Occurrences component was a massive function that had issues with hooks. Because React hooks doesn't allow early returns, a bug in occurrences rendering could not be resolved without a great refactoring.
Screenshots of the wanted result and the error log in issue: https://helsinkisolutionoffice.atlassian.net/browse/PT-911
> Splitted Occurrences component to multiple new private components.

- public/static/locales/en/enrolment.json
- public/static/locales/fi/enrolment.json
- public/static/locales/sv/enrolment.json
- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/ValidationSchema.tsx
- src/domain/enrolment/enrolmentForm/constants.ts
- src/domain/enrolment/utils.ts
PT-891. Enrolments does not require a phone number anymore.
Added missing required-attributes to emails and names. Removed required-attributes and validations from phone fields. 
Enrolment's email notifications are now mandatory. The checkbox is auto selected and disabled in UI, so it appears as checked but passive. GraphQL mutation does not allow sms only notifications anymore. It should be noted that API still allows them!
> Email is mandatory but phone number is optional in the enrolment form

- public/static/locales/en/enrolment.json
- public/static/locales/fi/enrolment.json
- public/static/locales/sv/enrolment.json
- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/utils.ts
PT-880. If no phone number field is filled, sms-notifications checkbox should be disabled and unchecked. If any of the phone number fields is filled, it should be enabled and free to use.
> Don't allow sms notifications if no phone number is given

- public/static/locales/en/event.json
- public/static/locales/fi/event.json
- public/static/locales/sv/event.json
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/eventBasicInfo/EventBasicInfo.tsx
- src/domain/event/utils.ts
- src/domain/events/__tests__/EventsPage.test.tsx
- src/domain/events/query.ts
- src/domain/events/utils.ts
- src/generated/graphql.tsx
PT-298 Events can be searched with organisationId. Added organisationId in events query arguments.
Show all events from provider link added to event basic information. Refactored organization information to a new OrganizationInfo -component. Added there a router link that would open a search page with organization parameter. Search by organization is still missing.
The query can now be made with organization -parameter, which should be an organizationId. E.g http://localhost:3000/fi?organization=T3JnYW5pc2F0aW9uTm9kZToy
> Show all events from provider link added to event basic information.

- src/domain/event/eventBasicInfo/EventBasicInfo.tsx
- src/domain/event/eventBasicInfo/eventBasicInfo.module.scss
PT-1109.
Too long url is now ellipsed and hidden.
> Fixed too long urls on event details page.

- public/locales/en/events.json
- public/locales/fi/events.json
- public/locales/sv/events.json
- src/domain/app/header/__tests__/Header.test.tsx
- src/domain/app/layout/__tests__/PageLayout.test.tsx
- src/domain/events/EventsPage.tsx
- src/domain/events/__tests__/EventsPage.test.tsx
- src/domain/events/constants.ts
Started using only 2 different events filters and sorters. Both are descending by start times, but another uses events from LinkedEvents and another uses occurrences from API.
PT-1150 PT-1154.
> refactor(events-list): New sorters and filters for events.

- public/locales/en/event.json
- public/locales/fi/event.json
- public/locales/sv/event.json
- src/__tests__/cms-page/[...slug].test.tsx
- src/domain/event/eventCard/EventCard.tsx
- src/domain/events/EventsPage.tsx
- src/domain/events/__tests__/EventsPage.test.tsx
- src/domain/neighborhood/divisionSelector/__tests__/DivisionSelector.test.tsx
- src/utils/mockDataUtils.ts
- Dont show upcoming occurrences in event card when there is none
- Show "No upcoming occurrences" text when event has no more upcoming occurrences
**[PT-1208](https://helsinkisolutionoffice.atlassian.net/browse/PT-1208):**
**[PT-1164](https://helsinkisolutionoffice.atlassian.net/browse/PT-1164):**
> fix: dont show upcoming occurrences in event card when there is none

- public/locales/en/event.json
- public/locales/fi/event.json
- public/locales/sv/event.json
- src/domain/event/EventPage.tsx
- src/domain/event/eventPage.module.scss
- Extends existing translations so that they contain information about unreliable mail traffic
- Adds margin to the notification
**[PT-1224](https://helsinkisolutionoffice.atlassian.net/browse/PT-1224):**
[PT-1216](https://helsinkisolutionoffice.atlassian.net/browse/PT-1216)
> PT-1224 | Add notice about unreliable mail traffic

- package.json
- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
- src/common/components/formikPersist/FormikPersist.tsx
- src/common/components/formikPersist/__tests__/FormikPersist.test.tsx
- src/constants.ts
- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/enrolment/__tests__/__snapshots__/CreateEnrolmentPage.test.tsx.snap
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/enrolmentForm.module.scss
- src/hooks/useIsMounted.ts
- src/setupTests.ts
- yarn.lock
- Add FormikPersts component to handle persisting and filling form from local storage
**[PT-1252](https://helsinkisolutionoffice.atlassian.net/browse/PT-1252):**
> PT-1252 | Initialize enrolment form from local storage if possible

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
- src/domain/place/placeText/PlaceText.tsx
- src/domain/place/query.ts
- src/domain/place/unitSelector/UnitPlaceSelector.tsx
- src/generated/graphql.tsx
- src/tests/apollo-mocks/schoolsAndKindergartensListMock.ts
API returns all the units (1000+ pcs) all at once from schoolsAndKindergartens graphql query. The Enrolment form autosuggest field for unit selection should be able to filter the list of units with an input value.
PT-1314.
----
The list of schools and kindergartens is from Servicemap API, but the selected place is queried from LinkedEvents places-API
Selected:
With error:
> feat: unit place selector uses schoolsAndKindergartens query

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/domain/event/EventPage.tsx
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/events/eventList/EventList.tsx
- src/utils/extractLatestReturnPath.ts
- src/utils/queryString.ts
- Event page back button now navigates to correct page preserving query parameters
**[PT-1293](https://helsinkisolutionoffice.atlassian.net/browse/PT-1293):**
> feat: event back button navigates to correct page

- src/constants.ts
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/__tests__/EnrolmentForm.test.tsx
- src/domain/enrolment/enrolmentForm/constants.ts
- src/domain/event/__tests__/enrolmentFormIntegration.test.tsx
- src/domain/event/occurrences/EnrolmentFormSection.tsx
- src/domain/events/eventSearchForm/EventSearchForm.tsx
- src/domain/keyword/constants.ts
- src/utils/__tests__/recommendedEventsUtils.test.ts
- src/utils/recommendedEventsUtils.ts
- Save recommended events variables from enrolment form to local storage
**[PT-1288](https://helsinkisolutionoffice.atlassian.net/browse/PT-1288):**
**[PT-1342](https://helsinkisolutionoffice.atlassian.net/browse/PT-1342):**
> PT-1288, PT-1342 | Save recommended events variables from enrolment form to local storage

- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/__tests__/enrolmentFormIntegration.test.tsx
- src/domain/event/occurrences/OccurrencesTable.tsx
- Add language column to occurrences table in event page
**[PT-1316](https://helsinkisolutionoffice.atlassian.net/browse/PT-1316):**
> PT-1316 | Add language column to occurrences table in event page

- src/domain/event/eventCard/EventCard.tsx
- src/domain/events/__tests__/EventCard.test.tsx
- src/domain/occurrences/query.ts
- src/generated/graphql.tsx
- src/utils/mockDataUtils.ts
PT-1310. NOTE: this needs https://github.com/City-of-Helsinki/palvelutarjotin/pull/229 to be merged.
> fix: event card should show upcoming occurrences only, no matter the enrolment time

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/domain/errorPage/ErrorPage.tsx
- src/domain/notFoundPage/NotFoundPage.tsx
- src/domain/notFoundPage/__tests__/NotFoundPage.test.tsx
- src/pages/404.tsx
- src/pages/_error.tsx
Adds a dedicated 404 page. Currently the generic error page and 404 page are identical in content.
Changes copy within the not found page to hint of the release of the new kultus, as described in the ticket.
Updates `_error.tsx` to use static generation.
**[PT-1334](https://helsinkisolutionoffice.atlassian.net/browse/PT-1334):**
> PT-1334 | Add notice about new service to 404 page

- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/ValidationSchema.tsx
- src/domain/enrolment/enrolmentForm/__tests__/EnrolmentForm.test.tsx
- src/domain/enrolment/enrolmentForm/__tests__/__snapshots__/EnrolmentForm.test.tsx.snap
- src/domain/enrolment/enrolmentForm/constants.ts
- src/domain/event/__tests__/__snapshots__/enrolmentFormIntegration.test.tsx.snap
- src/domain/event/occurrences/EnrolmentFormSection.tsx
- src/domain/event/occurrences/OccurrenceInfo.tsx
Persisting min and maxGroupSize values that were only used for validation was causing problems because previous values would be taken from local storage. To fix this min and MaxGroupSize values are now passed ar parameters to getValidationSchema to avoid persisting them to local storage.
**[PT-1347](https://helsinkisolutionoffice.atlassian.net/browse/PT-1347):**
> PT-1347 | Fix enrolment form group size validation bug

- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/occurrences/OccurrencesTable.tsx
-  Show date span in occurrence table for multi day occurrences
**[PT-1350](https://helsinkisolutionoffice.atlassian.net/browse/PT-1350):**
> PT-1350 | Show date span in occurrence table for multi day occurrences

- public/locales/en/event.json
- public/locales/fi/event.json
- public/locales/sv/event.json
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/occurrences/EnrolmentButtonCell.tsx
- src/domain/event/occurrences/EnrolmentError.tsx
- src/domain/event/occurrences/OccurrenceEnrolmentButton.tsx
- src/domain/event/occurrences/OccurrenceInfo.tsx
- src/domain/event/occurrences/OccurrencesTable.tsx
- src/domain/event/occurrences/occurrences.module.scss
- src/domain/event/occurrences/utils.ts
- src/domain/event/utils.ts
- src/domain/occurrence/utils.ts
- src/utils/dateUtils.ts
- src/utils/time/format.ts
Hide enrolment button until enrolling has begun.
Instead show text that describes when enrolment will begin.
Also contains:
* Handles error states within additional information
**[PT-1358](https://helsinkisolutionoffice.atlassian.net/browse/PT-1358):**
Added a test case to check that the button does not exist if enrolment has not begun. A lot of tests already so I was a bit hesitant whether I should add to the maintenance load. In the end I thought that this behaviour is worth testing as it has a big enough impact on UX and could be easy to break because there's a lot of boolean logic where this button is declared. Can be dropped if not.
> PT-1358 | Disallow enrolling when it has not begun

- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/__tests__/__snapshots__/enrolmentFormIntegration.test.tsx.snap
- src/domain/event/__tests__/enrolmentFormIntegration.test.tsx
- src/domain/event/occurrences/OccurrencesTable.tsx
- src/domain/event/occurrences/utils.ts
- Update some test to use inline snapshot
- Fix issue with languages that have underscore in their ID
- Order languages correctly (fi, sv...)
**[PT-1316](https://helsinkisolutionoffice.atlassian.net/browse/PT-1316):**
> fix: change language order in occurrence table to be fi, sv first

- package.json
- src/domain/app/header/HeaderNotification.tsx
- src/domain/app/header/__tests__/HeaderNotification.test.tsx
- src/utils/hash.ts
- yarn.lock
Notification hash and closed state are persisted to local storage. Notification is visible to the user again if any of the notification fields are changed in the CMS. Hash that is generated from the notification fields is saved to local storage and always compared with the one fetched from the CMS
**[PT-1337](https://helsinkisolutionoffice.atlassian.net/browse/PT-1337):**
> PT-1337 | Use local storage to remember if user close notification

- public/locales/en/event.json
- public/locales/fi/event.json
- public/locales/sv/event.json
- src/domain/event/EventPage.tsx
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/occurrences/OccurrencesTable.tsx
- src/domain/event/occurrences/occurrences.module.scss
- Disable checkboxes in occurrence table if enrolment hasn't started
- Hide disabled enrolment button for multi occurrence events if enrolment hasn't started
- Add notification about enrolment starting time if it hasn't started yet
**[PT-1401](https://helsinkisolutionoffice.atlassian.net/browse/PT-1401):**
- Couple additions to current tests to test notification
> PT-1401 | Add notification on top of occurrences table if enrolment hasn't started

- src/common/components/externalLink/ExternalLink.tsx
- src/common/components/externalLink/__tests__/ExternalLink.test.tsx
- src/domain/event/occurrences/EnrolmentButtonCell.tsx
- src/domain/event/occurrences/OccurrenceEnrolmentButton.tsx
- src/utils/isEmail.ts
- Add support for email link for enrolment button
**[PT-1321](https://helsinkisolutionoffice.atlassian.net/browse/PT-1321):**
- Should open email client when clicking enrolment link:
test url: http://localhost:3000/event/palvelutarjotin:af6z672j6m
> PT-1321 | Add support for email link for enrolment button

- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/eventBasicInfo/EventBasicInfo.tsx
Show organisations other event button was linking to front page which doesn't support searching with organisation id. Update link to go to event search page.
**[PT-1477](https://helsinkisolutionoffice.atlassian.net/browse/PT-1477):**
> PT-1477 |  Update organisation events link to target correct page

- src/headless-cms/components/cmsPageContent.module.scss
Image from CMS was rendered too big (pushed sidebar too small) and was not aligned very well.
> Add img and figure styles to fix cms page with big image

- package.json
- public/locales/en/events.json
- public/locales/fi/events.json
- public/locales/sv/events.json
- src/common/components/form/fields/CheckboxField.tsx
- src/domain/events/EventsSearchPage.tsx
- src/domain/events/__tests__/EventsSearchPage.test.tsx
- src/domain/events/eventSearchForm/EventSearchForm.tsx
- src/domain/events/eventSearchForm/eventSearchForm.module.scss
- src/domain/events/utils.ts
PT-1437 PT-1440
3 results without filter (2 of them are free):
When the isFree checkbox is checked, only 2 results are visible (and they both are free)
> feat(search): added a isFree -filter to the events search

- src/domain/events/EventsSearchPage.tsx
Selected sort state for the list of events is persisted.
**[PT-1438](https://helsinkisolutionoffice.atlassian.net/browse/PT-1438):** As a teacher, when browsing events, I want "last modified" order to stay if I have chosen it
**TODO**
> PT-1438 | Save EventSearchPage sort state to localStorage

- src/domain/app/header/Header.tsx
- src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
Adds root page links as the first link in the dropdown so that the root page is more easily accessible.
**[PT-1496](https://helsinkisolutionoffice.atlassian.net/browse/PT-1496)**
> PT-1496 | Add root navigation item as the first link

- src/domain/events/__tests__/EventsSearchPage.test.tsx
**[PT-1497](https://helsinkisolutionoffice.atlassian.net/browse/PT-1497)**
```
yarn jest src/domain/events/__tests__/EventsSearchPage.test.tsx -t "saves sort state to local storage"
```
> PT-1438 PT-1497 | Add a test for storing event search sort to local storage

- src/domain/events/EventsSearchPage.tsx
- src/domain/events/__tests__/EventsSearchPage.test.tsx
- src/domain/events/utils.ts
PT-1479. AllOngoingAnd-param uses an index in the LinkedEvents, but it's often not in sync
> feat(search): use text-param instead of allOngoingAnd

- .env.local.example
- README.md
Update README:
- Add production environment URL
- Add steps to setting up palvelutarjotin-ui locally
- Mention that NEXT_PUBLIC_CAPTCHA_KEY is required for the application
to work correctly
- Remove unnecessary names for URLs that are same or almost the same
as the URL, now the names can not go out of sync with the URLs
- Make reCAPTCHA related links to named links to save space
Update .env.local.example:
- Add working value for NEXT_PUBLIC_CAPTCHA_KEY for local development
from reCAPTCHA FAQ [1]. Tested the site key locally and it worked
even though the README says we're using reCAPTCHA v3 but the
reCAPTCHA FAQ says that the site key is for reCAPTCHA v2.
- Set NEXT_PUBLIC_API_BASE_URL to use the default port 8081 used by the
palvelutarjotin API backend
[1] Quote from …
> PT-1569 | update and clean up README, add captcha key to .env.local.example

- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
- src/domain/studyLevel/useStudyLevels.ts
NOTE: There is TECHNICAL DEBT:
- The ordinal number translations could be done using i18next but that would require at least v21.0.0 of i18next which is a major breaking release.
- Without upgrading to at least v21.0.0 i18next just using a hardcoded support for translating ordinal study level grades with keys:
- grade1 for study level grade 1
- grade2 for study level grade 2
- grade3   for study level grade 3
- grade_with_count for study level grades > 3
refs PT-1573
**[PT-1573](https://helsinkisolutionoffice.atlassian.net/browse/PT-1573)**
- ![fi](https://user-images.githubusercontent.com/77663720/221417970-e0a0b1ac-a221-44c4-850b-13d628be54fc.png)
- ![en](https://user-images.githubusercontent.com/77663720/221417972-36cf704a-fc9b-4032-9074-ace19ed5e233.png)
- …
> PT-1573 | fix study level grade translations, e.g. "3rd class"

- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/ValidationSchema.tsx
- src/domain/enrolment/enrolmentForm/__tests__/EnrolmentForm.test.tsx
PT-1605.
Require the phone number from the person of the  study group
while doing the enrolment or enrolment enquiry.
----
NOTE: Based on #269! So, also updated the React, Typescript, Eslint and the Jest runner! 
Installed a SWC binding for Jest and a plugin
to handle Jest compatibility issues. This approach was already tested in the events-helsinki-monorepo: https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/197. The tests are now twice as fast as before (but some of them are still quite slow).
> Require phone number when enrolling

- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
- src/domain/event/EventPage.tsx
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/eventPage.module.scss
- src/domain/event/utils.ts
PT-1686
Move enrol to queue button below the occurrences table. Change the style and the text of the heading.
PT-1678
The event queue form should be hidden when there are no occurrences
PT-1677
The event queue form should be available only for the events with internal enrolment when the enrolment period has already started.
Second try for #287 .
----
The form can be opened and used
> Move enrol to queue button below the occurrences table and hide it when queue should not be possible

- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
- src/domain/event/occurrences/EnrolmentFormSection.tsx
refs PT-1695
[PT-1695](https://helsinkisolutionoffice.atlassian.net/browse/PT-1695)
Tested locally:
[PT-1695]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1695 | feat: add specific toast error message for event full when enrolling

- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
closes PT-1694
[PT-1694](https://helsinkisolutionoffice.atlassian.net/browse/PT-1694)
[PT-1694]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1694 | feat: update extra needs field's helper text

- src/constants.ts
- src/domain/event/occurrences/EnrolmentFormSection.tsx
- src/domain/event/occurrences/QueueFormSection.tsx
default autoclose for toast error messages is 5s, this doubles that to
give users more time to read the message
refs PT-1695
[PT-1695](https://helsinkisolutionoffice.atlassian.net/browse/PT-1695)
[PT-1695]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1695 | fix(toast): automatically close toast error messages after 10s

- src/common/components/keyword/KeywordsList.tsx
- src/domain/events/EventsSearchPage.tsx
- src/domain/events/__tests__/EventsSearchPage.test.tsx
- src/domain/events/query.ts
- src/domain/events/utils.ts
- src/generated/graphql-cms.tsx
- src/generated/graphql-unified-search.tsx
- src/generated/graphql.tsx
PT-1591.
Update the GraphQL schemas: Add KeywordAnd-filter to events list query.
The new keywordAnd filter is now used instead of the keyword-filter,
which means that all the selected keywords narrows down 
the search results list instead of growing it.
There is an alternative or "extension" for this in https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/307
> feat: use keywordAnd-filter in events list query for keywords

- public/locales/en/event.json
- public/locales/fi/event.json
refs PT-1614
[PT-1614](https://helsinkisolutionoffice.atlassian.net/browse/PT-1614)
[PT-1614]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1614 | Fix "Share Event" translation

- next.config.js
- src/assets/styles/layout.scss
- src/common/components/multiSelectDropdown/dropdownMenu.module.scss
- src/common/components/table/table.module.scss
- src/domain/app/header/Header.tsx
- src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
- src/domain/app/header/header.module.scss
- src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
- src/domain/app/layout/container.module.scss
- src/domain/app/layout/pageLayout.module.scss
- src/domain/enrolment/enrolmentForm/enrolmentForm.module.scss
- src/domain/errorPage/errorPage.module.scss
- src/domain/event/eventBasicInfo/eventBasicInfo.module.scss
- src/domain/event/eventCard/eventCard.module.scss
- src/domain/event/eventPage.module.scss
- src/domain/event/occurrences/occurrences.module.scss
- src/domain/events/eventList/eventList.module.scss
- src/domain/events/eventSearchForm/eventSearchForm.module.scss
- src/domain/events/eventsPage.module.scss
- src/domain/newsletter/newsletterSubscribeForm/newsletterSubscribeForm.module.scss
- src/utils/stringifyUrlObject.ts
old breakpoint name (old breakpoint width) / new name (new width):
- sm (768px) -> m (768px) = $breakpoint-m in HDS v3.7
- md (992px) -> l (992px) = $breakpoint-l in HDS v3.7
- xlg (1600px) -> xxl (1600px), a custom breakpoint, not in HDS v3.7
refs PT-1720 (cleaning up / refactoring after the fact)
refs PT-1720 (cleaning up / refactoring)
refs PT-1720 (cleanup / refactoring after the fact)
[PT-1720](https://helsinkisolutionoffice.atlassian.net/browse/PT-1720)
https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/304
[PT-1720]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1720 | Refactoring & cleaning up

- src/__tests__/cms-page/[...slug].test.tsx
- src/domain/enrolment/enrolmentForm/__tests__/EnrolmentForm.test.tsx
- src/domain/place/query.ts
- src/domain/place/unitSelector/UnitPlaceSelector.tsx
- src/generated/graphql-cms.tsx
- src/generated/graphql.tsx
- src/headless-cms/__tests__/utils.test.ts
- src/tests/apollo-mocks/schoolsAndKindergartensListMock.ts
- src/utils/cmsMockDataUtils.ts
- testcafe/e2e/changeLanguage.ts
- testcafe/selectors/header.ts
PT-1733 PT-1743.
The unit place selector now uses a schools and kindergaratens list query with search-filter-parameter, since the API has changed the data source and the service now supports using it. So instead of always loading everything to memory, the client now requests a new options everytime when the search input changes.
NOTE: Needs https://github.com/City-of-Helsinki/palvelutarjotin/pull/350 as a dependency.
> feat: unit place selector search filter parameter

- src/domain/app/footer/Footer.tsx
- src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
- src/headless-cms/__tests__/utils.test.ts
- src/headless-cms/cmsApolloClient.ts
- src/headless-cms/config.ts
- src/headless-cms/constants.ts
- src/headless-cms/utils.ts
- src/pages/_app.tsx
- src/tests/apollo-mocks/menuMocks.ts
- src/tests/fixtures/menus/Palvelutarjotin all UIs Header (EN).ts
- src/tests/fixtures/menus/Palvelutarjotin all UIs Header (FI).ts
- src/tests/fixtures/menus/Palvelutarjotin all UIs Header (SV).ts
- src/tests/fixtures/menus/Palvelutarjotin-UI Footer (EN).ts
- src/tests/fixtures/menus/Palvelutarjotin-UI Footer (FI).ts
- src/tests/fixtures/menus/Palvelutarjotin-UI Footer (SV).ts
- src/tests/fixtures/menus/README.md
- src/tests/fixtures/menus/types.ts
**NOTE**:
- This will **only** fetch **CMS pages** that are in a **menu** in some language or that are a translation of a page that is in a menu
fixes:
- getAllMenuPages was using an obsolete menu, changed it to use the
new menus after HDS 3 upgrade in PR #304 i.e.
commit c64b314d5b4bc2f4a95251c5cb158032b2f85dad in master branch
- footer CMS page links were broken, fixed them to use the /cms-page/
- getAllMenuPages wasn't fetching footer CMS pages at all, added them
also:
- use AppConfig.cmsGraphqlEndpoint where applicable
- fix name passed to getEnvOrError in AppConfig.cmsGraphqlEndpoint
refs PT-1723
[PT-1723](https://helsinkisolutionoffice.atlassian.net/browse/PT-1723)
Footer is empty in review environment, probably a configuration issue.
You can try locally running the application to …
> PT-1723 | fix: getAllMenuPages, footer CMS page links, remove obsolete menus

- src/domain/events/EventsSearchPage.tsx
- src/domain/events/__tests__/EventsSearchPage.test.tsx
- src/domain/events/query.ts
- src/domain/events/utils.ts
- src/generated/graphql.tsx
PT-1591.
Update the GraphQL schemas: Add KeywordOrSet filters to events list query.
The keyword-filter is now replaced with 3 new KeywordOrSet filters:
keywordOrSet1, keywordOrSet2 and keywordOrSet3, because there
are 3 different keyword set types in Kultus search -- target groups,
categories and activities / additional criterias.
----
This PR needs the new filters from the API: https://github.com/City-of-Helsinki/palvelutarjotin/pull/341
NOTE: This can also act as an alternative for https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/306
> feat: use keywordOrSet-filter in events list query for keywords

- src/domain/app/footer/Footer.tsx
- src/headless-cms/__tests__/utils.test.ts
- src/headless-cms/utils.ts
- src/pages/_app.tsx
refs PT-1752
[PT-1752](https://helsinkisolutionoffice.atlassian.net/browse/PT-1752)
Manually tested all footer links in PR's review environment using Finnish, Swedish and English.
All links worked except "Give feedback" but that's a CMS configuration issue, meaning
that the page pointed to by the URL given in the CMS doesn't exist anymore and should
be updated in the CMS.
[PT-1752]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1752 | Fix resolving internal URLs to known non-CMS pages e.g. /newsletter/

- src/assets/styles/main.scss
- src/common/components/multiSelectDropdown/MultiSelectDropdown.tsx
- src/common/components/multiSelectDropdown/multiSelectDropdown.module.scss
**[PT-1753](https://helsinkisolutionoffice.atlassian.net/browse/PT-1753):**
[PT-1753]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1753 | Dropdown keyboard navigation logic

- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/ValidationSchema.tsx
- src/domain/enrolment/enrolmentForm/__tests__/EnrolmentForm.test.tsx
PT-1772.
The group sizes can be left empty, especially when 1 group is set to fill the event. In those cases, the group size children and adult inputs should not validate themselves against the unset limits. The fields should only be required when the limits are not set.
> fix: group size field validation when no limits are set

- src/headless-cms/components/CmsPageSearch/CmsPageSearch.tsx
PT-1771.
Instead of fetching 10 items to a grid that has 3 columns, fetch 9 items, so they are equally balanced in the grid.
> fix: set CMS page search size to better fit on grid implementation

- Dockerfile
- docker-compose.yml
now "docker compose up --build" spins up a development build locally,
hot reloading on Windows 11 + Docker Desktop didn't work, but that
may be Windows + WSL2 specific setup problem, see the following:
- https://github.com/vercel/next.js/issues/36774
- https://github.com/microsoft/WSL/issues/4739
also:
- remove deprecated version number from docker-compose.yml
refs PT-1792
[PT-1792](https://helsinkisolutionoffice.atlassian.net/browse/PT-1792)
[PT-1792]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1792 | Fix development stage of Dockerfile & add volume mappings for docker compose

- Dockerfile
- docker-compose.yml
- next.config.js
WATCHPACK_POLLING is enabled by default to use file change polling so
hot reload works more easily out-of-the-box
Tested and hot reload worked on Windows 11 + Docker Desktop + WSL2
using "docker compose up --build" and keeping the source code on the
host's NTFS file system, not inside the Linux file system in WSL2.
refs PT-1792
- [PT-1792](https://helsinkisolutionoffice.atlassian.net/browse/PT-1792)
- PR #341 
[PT-1792]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1792 | Fix hot reload in docker development

- src/common/components/table/table.module.scss
- src/domain/app/header/Header.tsx
- src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
- src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
- src/domain/app/layout/pageLayout.module.scss
- src/domain/event/eventImage/eventImage.module.scss
- src/domain/event/eventPage.module.scss
- src/domain/event/occurrences/occurrences.module.scss
The layout was broken due to the wrong markup in multiple components
1. Hero: mobile markup should be completely different with opposite positioning for child containers
2. Occurrences section: table and time fields positioning refactored. Table now has a horizontal scroll, that was the main component which was breaking layout and header specifically
3. Queue: repositioned in mobile
4. Share:  repositioned in mobile
5. Removed huge margin bottom in mobile between content and footer.
Please test the desktop and mobile view.
Still question, how usable the table is on mobile. User has to scroll to see the Details button, and then when details are expanded, user sees the most right content.
Hero in mobile:
Header expanded:
Mobile content of the event page:
With scrolled table to right:
With …
> Event page mobile payout

- .env
- Dockerfile
- package.json
- src/pages/cms-page/[...slug].tsx
PT-1837.
Use `SKIP_BUILD_STATIC_GENERATION=1` to skip static page generation.
> feat: skip build static generation with env-variable

- src/domain/enrolment/enrolmentForm/enrolmentForm.module.scss
- src/domain/event/occurrences/occurrences.module.scss
PT-1840
Fixes the place description and enrolment form heading lining
> fix(style): white-space wrapping in enrolment form and event details

- src/headless-cms/__tests__/utils.test.ts
- src/headless-cms/config.ts
PT-1840.
The images were fixed with last commit related to this, but then the sublinks, etc inside the page are not working. The rule was too strict, when it was first too loose -- Now it should be fixed.
> fix: cms rewriting rule

- src/common/components/keyword/EnrolmentStatusKeyword.tsx
- src/common/components/keyword/KeywordsList.tsx
- src/common/components/keyword/__tests__/KeywordsList.test.tsx
- src/domain/event/eventBasicInfo/EventBasicInfo.tsx
- src/domain/event/eventCard/EventCard.tsx
PT-1844.
The actual rehydration issue came from the useTranslation hook, which was not imported from the next-i18next, but from the react-i18next. Because of that, the result some how differed between the renders (from SSR and client).
The EnrolmentStatusKeyword was also rendered without LI-element, even then when it was rendered inside an UL-element. That is invalid against HTML standard.
Also, some key-attributes are now added with some uniqueID prefixes, because otherwise React struggled to identify the unique keyword items. This could have been an issue during rerenders. It was warned in the console.
> fix: rehydration issue in event cards keywords and enrolment statuses

- .github/dependabot.yml
Remove inexistent kuva-frontend team from dependabot reviewers
[PT-1864](https://helsinkisolutionoffice.atlassian.net/browse/PT-1864)
https://github.com/orgs/City-of-Helsinki/teams/kuva-frontend does not exist,
https://github.com/orgs/City-of-Helsinki/teams/kuva-front does exist but is not up to date
[PT-1864]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1864 | Remove inexistent kuva-frontend team from dependabot reviewers

- src/domain/app/header/HeaderNotification.tsx
- src/domain/app/header/__tests__/HeaderNotification.test.tsx
- src/domain/app/layout/__tests__/PageLayout.test.tsx
- src/tests/msw/server-handlers.ts
PT-1795.
There was an issue in CMS notification query, because it was using a
wrong Apollo Client. It was using the one meant not for Headless CMS but
for Kultus API.
> Fix notification query client usage

- package.json
- yarn.lock
Add resolutions in package.json to resolve packages to newer versions:
- @types/cookie
- To use the last known @types/cookie version, only for <v1 cookie.
NOTE: This can be removed if all dependencies start to depend on
`>=v1` cookie which provides the types itself
- hds-react/@babel/runtime
- To fix dependabot issue 111
NOTE: This can be removed if hds-react doesn't require a fixed
version of this package anymore
- hds-react/cookie
- To fix dependabot issue 101
NOTE: This can be removed if hds-react starts to depend on >=v1 cookie
Dependabot issues fixed by this commit:
https://github.com/City-of-Helsinki/palvelutarjotin-ui/security/dependabot/101
https://github.com/City-of-Helsinki/palvelutarjotin-ui/security/dependabot/111
Also:
- Update everything to latest minor using "ncu -i …
> PT-1884 | Resolve cookie & @babel/runtime to newer versions

- src/domain/event/BackButton.tsx
- src/domain/event/BackFromEventDetailsButton.tsx
- src/domain/event/EnrolmentFormContainer.tsx
- src/domain/event/EventHero.tsx
- src/domain/event/EventPage.tsx
- src/domain/event/QueryFormContainer.tsx
- src/domain/event/__tests__/EventPage.test.tsx
- src/domain/event/eventCard/EventCard.tsx
- src/domain/event/utils.ts
- src/domain/events/EventsPage.tsx
- src/domain/events/EventsSearchPage.tsx
- src/domain/events/__tests__/EventCard.test.tsx
- src/domain/events/__tests__/__snapshots__/EventCard.test.tsx.snap
- src/domain/events/__tests__/useHashlessReturnPathScrollFix.test.tsx
- src/domain/events/constants.ts
- src/domain/events/eventList/EventList.tsx
- src/domain/events/useHashlessReturnPathScrollFix.tsx
- src/utils/queryString.ts
PT-1886.
Steps to test:
1. Search an event
2. Click an event card to navigate to event details page
3. Use browser back button or back arrow -button in UI to navigate back to search page
Result: The serach results should be auto loaded (with Apollo cache) and user should be taken to the clicked card.
> Fix event details back button scroll restoration

- jest.config.js
- package.json
- src/constants.ts
- src/domain/enrolment/occurrenceTable/OccurrenceTable.tsx
- src/domain/event/occurrences/OccurrenceInfo.tsx
- src/domain/event/occurrences/OccurrencesTable.tsx
- src/utils/__tests__/dateUtils.test.ts
- src/utils/dateUtils.ts
- src/utils/time/format.ts
- yarn.lock
PT-1901 PT-1903.
The event dates and times should always be in Finnish timezone, no matter what location data is used.
Also, some dead code related to date handling removed.
> fix: all dates and times should always be fixed to Helsinki's timezone

- src/domain/headless-cms/components/CmsPageSearch/CmsPageSearch.tsx
PT-1913.
When the cards were listed in a grid of 3 cards (per row), the cards were quite unresponsive in a mobile view. When the layout direction is forced to "fixed-vertical", the result is much more responsive.
> fix: force direction of cards to vertical in cms page search component

- src/domain/app/header/Header.tsx
- src/domain/app/header/__tests__/useGetPathnameForLanguage.test.tsx
- src/domain/app/header/useCmsLanguageOptions.tsx
- src/domain/app/header/useCmsMenuItems.tsx
- src/domain/app/header/useGetPathnameForLanguage.tsx
- src/domain/headless-cms/__tests__/utils.test.ts
- src/domain/headless-cms/utils.ts
PT-1894.
The search filters were activated in search form properly, because the parameter names are case sensitive and the search params of the URL were lower cased.
Split the Header component code content to new hooks and util functions, so it's easier to manage and to understand, but also easier to test.
> Fix search params handling on language change and refactor header component

- .env.playwright.local.example
- .github/workflows/playwright.yml
- .gitignore
- README.md
- jest.config.js
- package.json
- playwright.config.ts
- src/domain/headless-cms/__tests__/config.test.ts
- src/domain/headless-cms/config.ts
- src/playwright/README.md
- src/playwright/constants.ts
- src/playwright/pages/accessibilityStatementCms.page.ts
- src/playwright/pages/base.page.ts
- src/playwright/pages/cms.page.ts
- src/playwright/pages/front.page.ts
- src/playwright/pages/search.page.ts
- src/playwright/pages/searchCapable.page.ts
- src/playwright/testWithFixtures.ts
- src/playwright/tests/accessibilityStatement.spec.ts
- src/playwright/tests/cookieConsent.ts
- src/playwright/tests/languageChange.spec.ts
- src/playwright/tests/search.spec.ts
- src/playwright/types.ts
- src/utils/__tests__/getCookieConsentGivenCookies.test.ts
- src/utils/getCookieConsentGivenCookies.ts
- tsconfig.json
- yarn.lock
Done:
- Add basic playwright tests
- Run the playwright tests in Github actions
[PT-1919](https://helsinkisolutionoffice.atlassian.net/browse/PT-1919)
See [src/playwright/README.md](https://github.com/City-of-Helsinki/palvelutarjotin-ui/blob/c1cf967cd2ba23e7ee941f8b741d6780832ffd28/src/playwright/README.md).
```bash
$ yarn playwright test
yarn run v1.22.22
$ C:\dev\projects\City-of-Helsinki\kultus-ui\node_modules\.bin\playwright test
Running 15 tests using 8 workers
15 passed (15.8s)
To open last HTML report run:
yarn playwright show-report
Done in 16.56s.
```
After running `yarn playwright test` I ran `yarn playwright show-report` and here's screenshot of that:
- ![playwright-show-report](https://github.com/user-attachments/assets/002219ed-02ab-4763-9cd8-ee4270dc2b73)
[PT-1919]: …
> PT-1919 | Add basic Playwright tests & run them in Github actions

- src/domain/event/occurrences/EnrolmentFormSection.tsx
- src/domain/event/occurrences/QueueFormSection.tsx
PT-1800.
The notifications of enrolment queue and enrolment reservation query are controlled with URL search parameters. Sync the queue enrolment and real enrolment URL search parameters so that the 2 notifications are not shown at the same time.
> fix: only 1 enrolment notification should be shown at once

- src/common/components/multiSelectDropdown/MultiSelectDropdown.tsx
- src/domain/events/eventSearchForm/__tests__/useFetchPlacesByIds.test.tsx
- src/domain/events/eventSearchForm/useFetchPlacesByIds.tsx
- src/domain/place/placeSelector/PlaceSelector.tsx
PT-1495.
Add a new hook that can be used to fetch multiple Place documents with a list of their ids.
When options were filtered and then some of them were selected, if the menu was closed, you could not unselect the selected options without searching them again with a filter feature.
All the selected optiosn are now always included in the results:
When the place selector does not have a search filter on, it shows the selected values:
> Fix place selector's critical accessibility issue
