City-of-Helsinki/palvelutarjotin-ui

public/static/locales/en/common.json
public/static/locales/en/event.json
public/static/locales/fi/common.json
public/static/locales/fi/event.json
public/static/locales/sv/common.json
public/static/locales/sv/event.json
src/domain/app/header/mobileNavbar/MobileNavbar.tsx
src/domain/app/header/navbar/Navbar.tsx
src/domain/app/layout/PageWrapper.tsx
src/domain/app/routes/constants.ts
src/domain/errorPage/ErrorPage.tsx
src/domain/errorPage/errorPage.module.scss
src/domain/event/EventPage.tsx
src/domain/events/EventsPage.tsx
src/domain/events/eventList/EventList.tsx
src/domain/notFoundPage/NotFoundPage.tsx
src/pages/_app.tsx
src/pages/event/[id].tsx

1. Generic error page
2. Not found page
3. PageWrapper component to show common meta data
4. Routing to event details page

PT-297 | Event page routing

---

public/static/locales/en/enrolment.json
public/static/locales/fi/enrolment.json
public/static/locales/sv/enrolment.json
src/domain/app/layout/pageLayout.module.scss
src/domain/enrolment/CreateEnrolmentPage.tsx
src/domain/enrolment/enrolmentPage.module.scss
src/domain/enrolment/eventInfo/EventInfo.tsx
src/domain/enrolment/eventInfo/eventInfo.module.scss
src/domain/event/query.ts
src/domain/organisation/query.ts
src/generated/graphql.tsx
src/pages/event/[eventId]/enrolment/create.tsx
src/pages/event/[eventId]/index.tsx

1. New page to create an enrolment
2. Event info on create enrolment page

PT-314, PT-316 | Route for create enrolment

---

src/domain/event/EventPage.tsx
src/domain/event/occurrences/Occurrences.tsx
src/domain/occurrence/utils.ts

Show error message if enrolment is not available

Enrolment error message

---

public/static/locales/en/common.json
public/static/locales/en/events.json
public/static/locales/fi/common.json
public/static/locales/fi/events.json
public/static/locales/sv/common.json
public/static/locales/sv/events.json
src/constants.ts
src/domain/events/eventSearchForm/EventSearchForm.tsx
src/domain/events/eventSearchForm/eventSearchForm.module.scss
src/domain/events/utils.ts
src/pages/event/[eventId]/index.tsx
src/utils/queryParameterToArray.ts

Added filter by language to search form in event page
**[PT-391](https://helsinkisolutionoffice.atlassian.net/browse/PT-391):**

Add filter events by language

---

src/domain/events/utils.ts

Add end time to events query
**[PT-423](https://helsinkisolutionoffice.atlassian.net/browse/PT-423):**

PT-423 | Add end time to events query

---

package.json
public/static/locales/en/common.json
public/static/locales/en/events.json
public/static/locales/fi/common.json
public/static/locales/fi/events.json
public/static/locales/sv/common.json
public/static/locales/sv/events.json
src/common/components/SrOnly/__tests__/SrOnly.test.tsx
src/common/components/SrOnly/__tests__/__snapshots__/SrOnly.test.tsx.snap
src/common/components/form/fields/DropdownField.tsx
src/common/components/form/fields/PlaceSelectorField.tsx
src/common/components/multiSelectDropdown/DropdownMenu.tsx
src/common/components/multiSelectDropdown/MultiSelectDropdown.tsx
src/common/components/multiSelectDropdown/dropdownMenu.module.scss
src/common/components/multiSelectDropdown/multiSelectDropdown.module.scss
src/common/components/scrollIntoViewWithFocus/ScrollIntoViewWithFocus.tsx
src/common/components/search/searchLabel/SearchLabel.tsx
src/common/components/search/searchLabel/searchLabel.module.scss
src/domain/event/__mocks__/eventWithOccurrences.json
src/domain/event/__tests__/EventPage.test.tsx
src/domain/events/eventSearchForm/EventSearchForm.tsx
src/domain/events/utils.ts
src/domain/place/placeSelector/PlaceSelector.tsx
src/generated/graphql.tsx
src/hooks/useDebounce.ts
yarn.lock

Add place component and filter to events search
**[PT-389](https://helsinkisolutionoffice.atlassian.net/browse/PT-389):**

PT-389 | Add place component and filter to events search

---

public/static/locales/en/events.json
public/static/locales/fi/events.json
public/static/locales/sv/events.json
src/common/components/datepicker/Datepicker.tsx
src/domain/events/eventSearchForm/EventSearchForm.tsx
src/domain/events/utils.ts

- Add end date field for events search
**[PT-444](https://helsinkisolutionoffice.atlassian.net/browse/PT-444):**

PT-444 | Add end date to events search

---

public/static/locales/en/enrolment.json
public/static/locales/fi/enrolment.json
public/static/locales/sv/enrolment.json
src/domain/event/occurrences/Occurrences.tsx

- change occurrence table seats title and display seatsTaken/amountOfSeats
**[PT-445](https://helsinkisolutionoffice.atlassian.net/browse/PT-445):**

PT-445 | change occurrence table seats title and display seatsTaken/amountOfSeats

---

src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx

- Move additional info textarea in enrolment form
**[PT-359](https://helsinkisolutionoffice.atlassian.net/browse/PT-359):**

PT-359 | Move additional info textarea in enrolment form

---

src/domain/enrolment/occurrenceTable/OccurrenceTable.tsx

Use same places left column in create enrolment page as in event details

Use same places left column in create enrolment page as in event details

---

src/constants.ts
src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx

Add privacy policy links to enrolment form
**[PT-178](https://helsinkisolutionoffice.atlassian.net/browse/PT-178):**

PT-178 | Add privacy policy links

---

package.json
public/static/locales/en/enrolment.json
public/static/locales/fi/enrolment.json
public/static/locales/sv/enrolment.json
src/domain/event/occurrences/Occurrences.tsx
src/domain/event/utils.ts
yarn.lock

- Show weekday in event card
- Show enrolment start date and time in occurrence table when enrolment hasn't started
**[PT-399](https://helsinkisolutionoffice.atlassian.net/browse/PT-399):** 
**[PT-458](https://helsinkisolutionoffice.atlassian.net/browse/PT-458):**

PT-399, PT-458 | Feature/event card weekday

---

public/static/locales/en/common.json
public/static/locales/fi/common.json
public/static/locales/sv/common.json
src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
src/domain/app/header/navbar/__tests__/__snapshots__/Navbar.test.tsx.snap
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
src/domain/events/__tests__/EventsPage.test.tsx
testcafe/e2e/changeLanguage.ts

- Rebrand texts to kultus beta
**[PT-473](https://helsinkisolutionoffice.atlassian.net/browse/PT-473):**

Rebrand texts to Kultus beta

---

public/static/locales/en/common.json
public/static/locales/fi/common.json
public/static/locales/sv/common.json
src/domain/accessibilityStatement/AccessibilityStatement.tsx
src/domain/accessibilityStatement/AccessibilityStatementEn.tsx
src/domain/accessibilityStatement/AccessibilityStatementFi.tsx
src/domain/accessibilityStatement/AccessibilityStatementSv.tsx
src/domain/accessibilityStatement/__test__/AccessibilityStatement.test.tsx
src/domain/accessibilityStatement/__test__/__snapshots__/AccessibilityStatement.test.tsx.snap
src/domain/accessibilityStatement/accessibilityStatement.module.scss
src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/footer/footer.module.scss
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
src/pages/accessibility/index.tsx
src/setupTests.ts

Add accessibility statement page and link to footer
**[PT-181](https://helsinkisolutionoffice.atlassian.net/browse/PT-181):**

PT-181 | Add accessibility statement

---

src/common/components/datepicker/__tests__/Datepicker.test.tsx
src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/event/__tests__/EventPage.test.tsx
src/domain/events/__tests__/EventsPage.test.tsx

Improve test performance by configuring defaultHidden to true.
[More info](https://testing-library.com/docs/dom-testing-library/api-queries#byrole)

Improve tets performance by setting defaultHidden: true

---

package.json
src/assets/styles/colours.scss
src/assets/styles/main.scss
src/common/components/datepicker/datepicker.module.scss
src/common/components/form/errorMessage.module.scss
src/common/components/loadingSpinner/loadingSpinner.module.scss
src/common/components/menuDropdown/menuDropdown.module.scss
src/common/components/multiSelectDropdown/dropdownMenu.module.scss
src/common/components/multiSelectDropdown/multiSelectDropdown.module.scss
src/common/components/search/searchLabel/searchLabel.module.scss
src/common/components/shareLinks/shareLinks.module.scss
src/common/components/table/table.module.scss
src/domain/app/header/mobileMenu/mobileMenu.module.scss
src/domain/app/header/mobileNavbar/mobileNavbar.module.scss
src/domain/app/header/navbar/navbar.module.scss
src/domain/app/layout/pageLayout.module.scss
src/domain/enrolment/CreateEnrolmentPage.tsx
src/domain/enrolment/enrolmentForm/enrolmentForm.module.scss
src/domain/enrolment/eventInfo/eventInfo.module.scss
src/domain/errorPage/errorPage.module.scss
src/domain/event/eventBasicInfo/eventBasicInfo.module.scss
src/domain/event/eventCard/eventCard.module.scss
src/domain/event/eventKeywords/eventKeywords.module.scss
src/domain/event/occurrences/occurrences.module.scss
src/domain/events/eventList/eventList.module.scss
src/domain/events/eventSearchForm/eventSearchForm.module.scss
src/domain/place/placeInfo/placeInfo.module.scss

- Update to use updated hds variables
**[PT-497](https://helsinkisolutionoffice.atlassian.net/browse/PT-497):**

PT-497 | update hds variables

---

src/domain/enrolment/CreateEnrolmentPage.tsx
src/domain/event/__mocks__/eventFragment.json
src/domain/event/__mocks__/eventWithOccurrences.json
src/domain/event/occurrences/__mocks__/occurrences.ts
src/domain/event/query.ts
src/domain/occurrence/query.ts
src/domain/occurrence/utils.ts
src/generated/graphql.tsx
src/utils/mockDataUtils.ts

- Update graphql types with codegen
- Update code to work :)
**[PT-549](https://helsinkisolutionoffice.atlassian.net/browse/PT-549):**

PT-549 |Update graphql types and code

---

public/static/locales/en/event.json
public/static/locales/fi/event.json
public/static/locales/sv/event.json
src/domain/venue/query.ts
src/domain/venue/utils.ts
src/domain/venue/venueInfo/VenueInfo.tsx
src/generated/graphql.tsx
src/utils/mockDataUtils.ts

- Add outdoor acitivty to Teacher's UI
**[PT-573](https://helsinkisolutionoffice.atlassian.net/browse/PT-573):**

PT-573 | Add outdoor activity

---

public/static/locales/en/common.json
public/static/locales/fi/common.json
public/static/locales/sv/common.json
src/assets/styles/common.scss
src/assets/styles/variables.scss
src/common/components/menuDropdown/menuDropdown.module.scss
src/domain/app/header/Header.tsx
src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
src/domain/app/header/header.module.scss
src/domain/app/layout/PageLayout.tsx
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap

- Add skip link
- Fix language selector focus outline
**[PT-584](https://helsinkisolutionoffice.atlassian.net/browse/PT-584):**

PT-584 | Add skip to content link and fix language selector focus outline

---

src/domain/event/dateFilter/DateFilter.tsx

PT-602: Fixes aria hidden attribute

---

public/static/locales/en/form.json
public/static/locales/fi/form.json
public/static/locales/sv/form.json
src/domain/app/forms/constants.ts
src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/enrolment/enrolmentForm/ValidationSchema.tsx

PT-752 Validate the sum of adults live, before enrolment is submitted.

Validate amount of adults after children count is given.

---

public/static/locales/en/events.json
public/static/locales/fi/events.json
public/static/locales/sv/events.json
src/domain/events/eventSearchForm/EventSearchForm.tsx

PT-751 | Change additional criteria field to Activities

---

public/static/locales/en/event.json
public/static/locales/fi/event.json
public/static/locales/sv/event.json
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/eventBasicInfo/EventBasicInfo.tsx
src/domain/event/eventBasicInfo/EventCategorisation.tsx
src/domain/event/eventBasicInfo/eventBasicInfo.module.scss
src/domain/event/eventKeywords/eventKeywords.module.scss
src/domain/event/query.ts
src/domain/event/utils.ts
src/domain/keyword/query.ts
src/generated/graphql.tsx
src/utils/keywordArrayToText.ts

-  Add categorisation section to event page

PT-619 | Add categorisation section to event page

---

public/static/locales/en/enrolment.json
public/static/locales/fi/enrolment.json
public/static/locales/sv/enrolment.json
src/domain/enrolment/enrolmentForm/constants.ts

PT-721 PT-828 There are so many language fields in enrolment form that they are confusing.

Changed enrolment form notification language label

---

public/static/locales/en/form.json
public/static/locales/fi/form.json
public/static/locales/sv/form.json
src/domain/event/occurrences/Occurrences.tsx
src/domain/place/placeInfo/PlaceInfo.tsx
src/domain/place/placeInfo/PlaceMapLink.tsx
src/domain/place/placeInfo/placeInfo.module.scss
src/domain/place/placeInfo/usePlaceMapLinks.tsx

PT-762. PlaceInfo is refactored to use new PlaceMapLink component, which have 2 render variants: a-element and button-element. UsePlaceMapLinks hook is added to help use of the new map link component.

Occurrences place info map links refactored to use new map link component.

---

package.json
src/domain/event/EventPage.tsx
src/domain/event/__tests__/EventPage.test.tsx

PT-870 | Fix event query to include target group

---

src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupInfo.tsx
src/domain/occurrence/query.ts
src/generated/graphql.tsx
src/utils/mockDataUtils.ts

PT-897. Pull request https://github.com/City-of-Helsinki/palvelutarjotin/pull/131 for API is needed for this pull request!

Support for new language API.

---

src/domain/enrolment/CreateEnrolmentPage.tsx
src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/event/EventPage.tsx
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/query.ts
src/generated/graphql.tsx

PT-581 Added an "upcoming" variable to event query's pEvent occurrences.

Only upcoming occurrences are listed on event pages

---

src/domain/event/occurrences/Occurrences.tsx

PT-851 - "As a teacher I want see weekday at enrolment occurence table."

Weekday shown in full in occurrence table.

---

public/static/locales/en/enrolment.json
public/static/locales/en/occurrence.json
public/static/locales/fi/common.json
public/static/locales/fi/enrolment.json
public/static/locales/fi/occurrence.json
public/static/locales/sv/enrolment.json
public/static/locales/sv/occurrence.json
src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupInfo.tsx
src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupLanguageInfo.tsx

PT-830. Fixes after testing #92 .
Screenshots: https://helsinkisolutionoffice.atlassian.net/browse/PT-830?focusedCommentId=23605

Fixes and some cleaning done to language translations.

---

src/domain/event/occurrences/Occurrences.tsx

PT-835 Show all events of this location -button opens a new window with a place search.
Button simple opens a new tab.

Implemented Show all events of this location -button feature.

---

public/static/locales/en/common.json
public/static/locales/fi/common.json
public/static/locales/sv/common.json
src/common/components/externalLink/ExternalLink.tsx
src/common/components/externalLink/__tests__/ExternalLink.test.tsx
src/common/components/externalLink/__tests__/__snapshots__/ExternalLink.test.tsx.snap
src/constants.ts
src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/footer/footer.module.scss
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap

PT-365 | Add feedback link

---

.github/workflows/ci.yml
.github/workflows/production.yml
.github/workflows/review.yml
.github/workflows/staging.yml
package.json
yarn.lock

Update workflows to be same as in tapahtumat-ui

Use same workflows & github messages and alerts as in tapahtumat workflows

---

public/static/locales/en/enrolment.json
public/static/locales/fi/enrolment.json
public/static/locales/sv/enrolment.json

PT-929 Added new missing (still sketchy) study level translations.

Added new study level translations.

---

src/domain/events/constants.ts
src/domain/events/eventSearchForm/useKeywordOptions.ts

PT-953: Add remote event categories to the top of dropdown options

---

public/static/locales/en/enrolment.json
public/static/locales/fi/enrolment.json
public/static/locales/sv/enrolment.json

Added translations for secondary level students.

---

src/domain/app/layout/pageLayout.module.scss

Merge style-lint fix

---

src/domain/events/EventsPage.tsx
src/domain/events/eventSearchForm/EventSearchForm.tsx
src/domain/events/eventSearchForm/eventSearchForm.module.scss
src/domain/events/filterSummary/FilterSummary.tsx
src/domain/events/filterSummary/filterButton/FilterButton.tsx
src/domain/events/filterSummary/filterButton/filterButton.module.scss
src/domain/events/filterSummary/filterSummary.module.scss
src/domain/events/query.ts
src/generated/graphql.tsx

Only provider filter is implemented

PT-986: Adds filter badges to the search form

---

public/static/locales/en/common.json
public/static/locales/fi/common.json
public/static/locales/sv/common.json
src/constants.ts
src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap

PT-1021: Adds link to pt admin

---

src/domain/events/EventsPage.tsx
src/domain/events/eventSearchForm/EventSearchForm.tsx

Fix publisher badge

---

src/domain/event/eventCard/EventCard.tsx
src/domain/events/__tests__/EventsPage.test.tsx

Showing short description in front page instead of the longer one.

---

src/common/components/textWithHTMLOrLineBreaks/TextWithHTMLOrLineBreaks.tsx
src/common/components/textWithHTMLOrLineBreaks/__tests__/TextWithHTMLOrLineBreaks.test.tsx
src/common/components/textWithHTMLOrLineBreaks/__tests__/__snapshots__/TextWithHTMLOrLineBreaks.test.tsx.snap
src/common/components/textWithLineBreaks/TextWithLineBreaks.tsx
src/common/components/textWithLineBreaks/__tests__/TextWithLineBreaks.test.tsx
src/common/components/textWithLineBreaks/__tests__/__snapshots__/TextWithLineBreaks.test.tsx.snap
src/domain/event/eventBasicInfo/EventBasicInfo.tsx

PT-547 PT-1061. Cloned the TextWithHTMLOrLineBreaks and TextWithLineBreaks components from the admin project.

Added new components to read the description with HTML-nodes.

---

src/generated/graphql.tsx
src/utils/mockDataUtils.ts

Updated the schema by adding a support for organisation proposals.

---

.husky/commit-msg
CHANGELOG.md
README.md
commitlint.config.js
package.json
yarn.lock

- Add standard version
**[PT-1108](https://helsinkisolutionoffice.atlassian.net/browse/PT-1108):**

PT-1108 | Add standard version

---

package.json
public/locales/en/event.json
public/locales/fi/event.json
public/locales/sv/event.json
src/common/components/skeletonLoader/SkeletonLoader.tsx
src/domain/event/eventCard/EventCard.tsx
src/domain/event/eventCard/eventCard.module.scss
src/domain/event/utils.ts
src/domain/events/__tests__/EventCard.test.tsx
src/domain/events/query.ts
src/domain/occurrences/query.ts
src/generated/graphql.tsx
yarn.lock

PT-1050 PT-1107.
NOTE: This needs new API https://github.com/City-of-Helsinki/palvelutarjotin/pull/191

Implementation of event cards other event times in front page.

---

src/domain/app/apollo/configureApollo.tsx
src/domain/event/EventPage.tsx
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/occurrences/Occurrences.tsx
src/server.js

- fix occurrences date filtering in single event page
**[PT-1132](https://helsinkisolutionoffice.atlassian.net/browse/PT-1132):**

PT-1132 | fix occurrences date filtering in single event page

---

src/domain/event/occurrences/Occurrences.tsx
src/domain/events/__tests__/EventCard.test.tsx
src/domain/occurrence/query.ts
src/generated/graphql.tsx

- Fix use event.offer instead of occurrence.linkedEvent to improve api perf
**[PT-1135](https://helsinkisolutionoffice.atlassian.net/browse/PT-1135):**

PT-1135 | Fix use event.offer instead of occurrence.linkedEvent to improve api perf

---

public/locales/en/cms.json
public/locales/fi/cms.json
public/locales/sv/cms.json
src/constants.ts
src/domain/app/header/Header.tsx
src/domain/app/routes/constants.ts
src/domain/app/routes/utils.ts
src/headless-cms/cmsApolloClient.ts
src/headless-cms/components/Breadcrumbs.tsx
src/headless-cms/components/CmsPage.tsx
src/headless-cms/components/CmsPageNavigation.tsx
src/headless-cms/components/CmsPageSearch/CmsPageSearch.tsx
src/headless-cms/components/cmsPage.module.scss
src/pages/cms-page/[...slug].tsx
src/utils/cmsMockDataUtils.ts

- Add breadcrumbs and improve sub page search layout

feat(cms): add breadcrumbs and improve sub page search layout

---

src/common/components/multiSelectDropdown/dropdownMenu.module.scss
src/domain/events/eventSearchForm/EventSearchForm.tsx

Reordered the search fields and fixed their drop down menus

---

src/domain/events/__tests__/EventsPage.test.tsx
src/domain/events/query.ts
src/domain/events/utils.ts
src/generated/graphql.tsx

- use allOngoingAnd parameter to get better search results
**[PT-1206](https://helsinkisolutionoffice.atlassian.net/browse/PT-1206):**

feat: use allOngoingAnd parameter to get better search results

---

src/__tests__/cms-page/[...slug].test.tsx

test: improve cms page tests

---

package.json
public/locales/en/occurrence.json
public/locales/fi/occurrence.json
public/locales/sv/occurrence.json
src/common/components/externalLink/ExternalLink.tsx
src/common/components/externalLink/__tests__/__snapshots__/ExternalLink.test.tsx.snap
src/domain/event/EventPage.tsx
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/constants.ts
src/domain/event/occurrences/EnrolmentButtonCell.tsx
src/domain/event/occurrences/Occurrences.tsx
src/domain/event/query.ts
src/domain/event/utils.ts
src/generated/graphql-cms.tsx
src/generated/graphql.tsx
src/utils/mockDataUtils.ts
yarn.lock

Added enrolment type enum and external enrolment url field to PalvelutarjotinEvent.
PT-849 PT-1103.

feat(enrolment-type): the enrolment type effects on views

---

src/domain/event/occurrences/EnrolmentButtonCell.tsx
src/domain/event/occurrences/Occurrences.tsx

- Fix enrolment button styling

fix: occurrences table enrolment button styling

---

public/locales/sv/common.json
public/locales/sv/enrolment.json
public/locales/sv/event.json
public/locales/sv/events.json
public/locales/sv/footer.json

Fix swedish translations
**[PT-1221](https://helsinkisolutionoffice.atlassian.net/browse/PT-1221):**

PT-1221 | Fix swedish translations

---

public/locales/en/enrolment.json
public/locales/fi/enrolment.json
public/locales/sv/enrolment.json
src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/neighborhood/divisionSelector/__tests__/DivisionSelector.test.tsx
src/headless-cms/utils.ts

fix: better translation for unit field checkbox

---

src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/place/placeText/PlaceText.tsx
src/domain/place/unitSelector/UnitPlaceSelector.tsx
src/tests/apollo-mocks/schoolsAndKindergartensListMock.ts

PT-1298. NOTE: Verification skipped because tests are still failing.

test: tests for UnitField

---

public/locales/en/events.json
public/locales/fi/events.json
public/locales/sv/events.json
src/domain/app/layout/container.module.scss
src/domain/bannerHero/BannerHero.tsx
src/domain/events/EventsPage.tsx
src/domain/events/__tests__/EventsPage.test.tsx
src/domain/events/eventsPage.module.scss
src/domain/keyword/query.ts
src/generated/graphql-cms.tsx
src/generated/graphql.tsx
src/utils/cmsMockDataUtils.ts
src/utils/mockDataUtils.ts

- Add popular keywords section to front page
**[PT-1268](https://helsinkisolutionoffice.atlassian.net/browse/PT-1268):**

PT-1268 | Add popular keywords section to front page

---

public/locales/en/occurrence.json
public/locales/fi/occurrence.json
public/locales/sv/occurrence.json
src/domain/event/occurrences/OccurrencesTable.tsx

- Add one last translation to new occurrence table
**[PT-1263](https://helsinkisolutionoffice.atlassian.net/browse/PT-1263):**

fix: add translation to select occurrence checkbox

---

public/locales/en/events.json
public/locales/fi/events.json
public/locales/sv/events.json
src/domain/enrolment/enrolmentForm/__tests__/__snapshots__/EnrolmentForm.test.tsx.snap
src/domain/events/EventsPage.tsx
src/domain/events/__tests__/EventsPage.test.tsx
src/domain/events/eventList/EventList.tsx
src/domain/events/query.ts
src/generated/graphql-cms.tsx
src/generated/graphql.tsx
src/utils/cmsMockDataUtils.ts

PT-1273 |  Use new upcoming events query in front page

---

src/domain/place/unitSelector/UnitPlaceSelector.tsx

fix: unit id fields entries are filtered in lowercase format

---

public/locales/en/events.json
public/locales/fi/events.json
public/locales/sv/events.json
src/common/components/keyword/Keyword.tsx
src/common/components/keyword/__tests__/__snapshots__/KeywordsList.test.tsx.snap
src/domain/event/__tests__/EventPage.test.tsx
src/domain/events/EventsSearchPage.tsx
src/domain/events/__tests__/EventsPage.test.tsx
src/domain/events/__tests__/EventsSearchPage.test.tsx
src/domain/events/eventSearchForm/EventSearchForm.tsx
src/domain/events/eventSearchForm/eventSearchForm.module.scss
src/domain/events/eventSearchForm/useKeywordOptions.ts
src/domain/events/filterSummary/FilterSummary.tsx
src/domain/events/filterSummary/filterButton/FilterButton.tsx
src/domain/events/filterSummary/filterButton/KeywordFilterButton.tsx
src/domain/events/filterSummary/filterSummary.module.scss

- Add clear filters button
- Add filter tags for categories that are not found in keyword sets
**[PT-1294](https://helsinkisolutionoffice.atlassian.net/browse/PT-1294):**

PT-1294 | Filter tags + clear filter button

---

src/domain/app/header/__tests__/HeaderNotification.test.tsx
src/domain/app/header/__tests__/__snapshots__/HeaderNotification.test.tsx.snap
src/domain/app/layout/__tests__/PageLayout.test.tsx

Fixes some test cases that expected old values.

Chore | Fix tests

---

src/domain/events/EventsPage.tsx
src/domain/events/__tests__/EventsPage.test.tsx
src/domain/events/query.ts
src/generated/graphql.tsx
src/utils/mockDataUtils.ts

fix: upcoming events query

---

src/headless-cms/components/CmsPageSearch/CmsPageSearch.tsx
src/headless-cms/components/CmsPageSearch/cmspagesearch.module.scss

- Fix cms cards :)
**[PT-1396](https://helsinkisolutionoffice.atlassian.net/browse/PT-1396):**

fix: cms card layout

---

public/locales/en/occurrence.json
public/locales/fi/occurrence.json
public/locales/sv/occurrence.json
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/__tests__/enrolmentFormIntegration.test.tsx
src/domain/event/occurrences/OccurrencesTable.tsx
src/headless-cms/components/CmsPageSearch/cmspagesearch.module.scss

- Add "Näytä tapahtuma-ajan lisätiedot" as aria label to "Näytä tiedot" button in occurrences table for better accessibility
- Fix image aspect ratio in cms cards

fix: add better abel for show mroe details button in occurrence table

---

README.md

- Added some documentation links
- Updated link where  reCAPTCHA credentials are found

Update reCAPTCHA docs

---

.github/workflows/production.yml
public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/domain/accessibilityStatement/AccessibilityStatementEn.tsx
src/domain/accessibilityStatement/AccessibilityStatementFi.tsx
src/domain/accessibilityStatement/AccessibilityStatementSv.tsx
src/domain/accessibilityStatement/__test__/__snapshots__/AccessibilityStatement.test.tsx.snap
src/domain/app/header/__tests__/HeaderNotification.test.tsx
src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
src/domain/app/header/__tests__/__snapshots__/HeaderNotification.test.tsx.snap
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
src/domain/events/EventsPage.tsx

- Update Kultus beta to Kultus
**[PT-1413](https://helsinkisolutionoffice.atlassian.net/browse/PT-1413):**

Update 'Kultus beta' texts to 'Kultus'

---

src/common/components/keyword/Keyword.tsx
src/common/components/keyword/KeywordsList.tsx
src/domain/event/eventCard/EventCard.tsx
src/domain/events/__tests__/__snapshots__/EventCard.test.tsx.snap

Resolve validate dom nesting issue by changing link to button
**[PT-1386](https://helsinkisolutionoffice.atlassian.net/browse/PT-1386):**

PT-1386 | Resolve validate dom nesting issue by changing link to button

---

src/domain/app/header/HeaderNotification.tsx
src/domain/app/header/__tests__/HeaderNotification.test.tsx
src/domain/app/layout/__tests__/PageLayout.test.tsx
src/generated/graphql-cms.tsx
src/generated/graphql.tsx
src/headless-cms/query.ts

- Added language parameter to Notification query

feat: add support for localization in notification

---

src/pages/api/newsletter/subscribe/[groupId].ts

fix(newsletter): added error message to generic newsletter api error

---

src/headless-cms/components/CmsPageSearch/CmsPageSearch.tsx

fix: make learning materials to link corretly in english and swedish

---

public/locales/sv/common.json
public/locales/sv/events.json
testcafe/e2e/changeLanguage.ts

Make changes to copy Katri requested.
**[PT-1442](https://helsinkisolutionoffice.atlassian.net/browse/PT-1442)**

PT-1442 | Change Swedish page title

---

src/domain/event/calendarButton/CalendarButton.tsx
src/domain/place/placeInfo/PlaceInfo.tsx
src/domain/place/placeInfo/usePlaceMapLinks.tsx
src/domain/place/placeText/PlaceText.tsx
src/domain/place/unitSelector/UnitPlaceSelector.tsx

fix: prevent fetching the places without place id

---

src/headless-cms/components/__tests__/CmsPage.test.tsx
src/utils/cmsMockDataUtils.ts

- Typescript issue fix + Post fake function

test: add fake function for Post and fix typing issues

---

src/pages/404.tsx
src/pages/_app.tsx
src/pages/_error.tsx
src/pages/cms-page/[...slug].tsx

Handle fallback situation in app.tsx to avoid strange behaviour when cms page is not found
**[PT-1476](https://helsinkisolutionoffice.atlassian.net/browse/PT-1476):**

PT-1476 | Handle situation when cms page is not found

---

public/locales/fi/enrolment.json

fix: a typo in the placeholder text "Etsi helsinkiläistä toimipistettä"

---

public/locales/en/newsletter.json
public/locales/fi/newsletter.json
public/locales/sv/newsletter.json
src/constants.ts
src/domain/newsletter/SubscribeNewsletterPage.tsx
src/domain/newsletter/__tests__/__snapshots__/SubscribeNewsletterPage.test.tsx.snap

chore(newsletter): add Gruppo -info text to the newsletter page

---

k6LoadTests.js

Virtual users of load test is adjusted to match reality 
**[DEVOPS-428](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-428):**

Virtual users of load test

---

src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
src/domain/enrolment/enrolmentForm/__tests__/EnrolmentForm.test.tsx

PT-1542 PT-1547
When creating enrolment:

Enrolments with 0 participants are not allowed

---

src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap

Fixed the footer terms of service link not having the current language in it.

PT-1560: Fix footer terms of service link i18n support

---

src/constants.ts
src/domain/newsletter/__tests__/__snapshots__/SubscribeNewsletterPage.test.tsx.snap

**[PT-1596](https://helsinkisolutionoffice.atlassian.net/browse/PT-1596): Update privacy policy link on teachers UI**

Update privacy policy links

---

public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/assets/styles/main.scss
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
src/domain/cookieConsent/CookieConsent.tsx
src/domain/enrolment/enrolmentForm/__tests__/__snapshots__/EnrolmentForm.test.tsx.snap
src/domain/matomo/Matomo.tsx
src/domain/matomo/__tests__/Matomo.test.tsx
src/pages/_app.tsx

feat: cookie consent implementation

---

public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/domain/cookieConsent/CookieConsent.tsx

fix: cookie consent translations

---

public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/domain/cookieConsent/CookieConsent.tsx

fix: essential cookies texts overrides

---

azure-pipelines-release.yml
azure-pipelines-review.yml
azure-pipelines-test.yml

**[DEVOPS-495](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495):**
[DEVOPS-495]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Azure DevOps pipelines

---

public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/domain/bannerHero/BannerHero.tsx
src/domain/bannerHero/bannerHero.module.scss
src/domain/events/EventsPage.tsx
src/domain/events/eventsPage.module.scss

refs PT-1606
**[PT-1606](https://helsinkisolutionoffice.atlassian.net/browse/PT-1606)**
[PT-1606]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1606 | fix: fix banner hero layout accessibility issue 4.1

---

public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/domain/bannerHero/bannerHero.module.scss
src/domain/events/__tests__/EventsPage.test.tsx
src/domain/events/eventsPage.module.scss
testcafe/e2e/changeLanguage.ts

refs PT-1606
**[PT-1606](https://helsinkisolutionoffice.atlassian.net/browse/PT-1606)**
[PT-1606]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1606 | fix: update banner hero texts and raise search box a bit

---

.env
.env.local.example
README.md
k6LoadTests.js
src/headless-cms/components/__tests__/CmsPage.test.tsx

refs PT-1650
–
**[PT-1650](https://helsinkisolutionoffice.atlassian.net/browse/PT-1650)**
[PT-1650]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1650 | chore: switch from KuVa to Platta environments

---

codegen.yml
public/locales/en/enrolment.json
public/locales/fi/enrolment.json
public/locales/sv/enrolment.json
src/domain/enrolment/constants.ts
src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
src/domain/enrolment/enrolmentForm/enrolmentForm.module.scss
src/domain/enrolment/utils.ts
src/domain/event/EventPage.tsx
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/__tests__/enrolmentFormIntegration.test.tsx
src/domain/event/eventPage.module.scss
src/domain/event/occurrences/QueueFormSection.tsx
src/domain/eventQueueEnrolment/mutation.ts
src/generated/graphql-cms.tsx
src/generated/graphql.tsx

PT-1655 Queue enrolment UI

---

Dockerfile

Use Node 20 in Dockerfile

---

src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
src/domain/cookieConsent/CookieConsent.tsx
src/domain/matomo/Matomo.tsx

fix: matomo update logic

---

CHANGELOG.md
README.md
package.json
yarn.lock

refs PT-1699
[PT-1699](https://helsinkisolutionoffice.atlassian.net/browse/PT-1699)
[PT-1699]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1699 | chore: remove standard-version as unneeded

---

src/domain/event/eventImage/eventImage.module.scss

fix: css image hero bug

---

README.md
src/domain/app/footer/__tests__/Footer.test.tsx
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/header/__tests__/HeaderNotification.test.tsx
src/domain/app/header/__tests__/__snapshots__/HeaderNotification.test.tsx.snap

feat: change domain to hel.fi

---

public/locales/en/enrolment.json
public/locales/fi/enrolment.json
public/locales/sv/enrolment.json
src/domain/studyLevel/useStudyLevels.ts

**[PT-1749](https://helsinkisolutionoffice.atlassian.net/browse/PT-1749):**
[PT-1749]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1749 | Suggested translations update

---

public/locales/en/event.json
public/locales/fi/event.json
public/locales/sv/event.json

PT-1782.
Remove the part of the message that mentions that the site is stil ludner development.

fix: update enrolment confirmation messages

---

package.json
public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
public/locales/sv/header.json
src/headless-cms/components/__tests__/CmsPage.test.tsx
src/pages/_app.tsx
yarn.lock

**[PT-1771](https://helsinkisolutionoffice.atlassian.net/browse/PT-1771):**
[PT-1771]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1771 | load more button styles configs

---

src/common/components/multiSelectDropdown/MultiSelectDropdown.tsx
src/hooks/useDropdownKeyboardNavigation.ts

fix: improve dropdown navigation

---

package.json
yarn.lock

fix: hcrc v1 major

---

src/headless-cms/__tests__/utils.test.ts
src/headless-cms/config.ts
src/headless-cms/utils.ts

PT-1843 PT-1840 PT-1837
Last fix to this fixed the most critical parts of this rewriting rule, but now
also the locale/language is taken care of.

fix: cms internal url rewriting

---

LICENSE

Add `LICENSE` file using MIT license
[PT-1877](https://helsinkisolutionoffice.atlassian.net/browse/PT-1877)
[PT-1877]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1877 | Add `LICENSE` file using MIT license

---

next.config.js

PT-1874.
See more:
https://nextjs.org/docs/14/pages/building-your-application/configuring/content-security-policy

feat(csp): add CSP header configuration

---

src/domain/event/BackFromEventDetailsButton.tsx
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/eventCard/EventCard.tsx
src/domain/events/EventsSearchPage.tsx
src/domain/events/constants.ts
src/domain/events/eventList/EventList.tsx
src/utils/queryString.ts

fix: back arrow -button scroll restoration

---

.husky/pre-commit
CHANGELOG.md
README.md
package.json
public/hds-favicon-kit/README.md
src/tests/fixtures/menus/README.md
yarn.lock

chore: add doctoc to pre-commit hook

---

jest.config.js

test: include ts-files in coverage report

---

README.md
package.json

Add Doctoc to dependencies and small note about yarn intsall to readme

---

yarn.lock

chore: add missing yarn lock entries

---

.github/dependabot.yml
CODEOWNERS

refs PT-1887 (palvelutarjotin)
refs RATYK-107 (similar changes in ratkaisutoimisto's projects)
[PT-1887](https://helsinkisolutionoffice.atlassian.net/browse/PT-1887)
[RATYK-107](https://helsinkisolutionoffice.atlassian.net/browse/RATYK-107)
[PT-1887]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RATYK-107]: https://helsinkisolutionoffice.atlassian.net/browse/RATYK-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PT-1887 | Replace dependabot reviewers with CODEOWNERS file
